## Exercícios

Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

In [3]:
import pandas as pd

## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil. 

### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [4]:
df1 = pd.read_csv('gasolina_2000+.csv')
df2 = pd.read_csv('gasolina_2010+.csv')
# pd.read_csv le o arquivo csv(Excel)
df3 = pd.concat([df1,df2])
# concat junto os dois DataFrames

C:\Users\NAYRA BRAGA\AppData\Local\Temp\ipykernel_16092\3480658593.py:2: DtypeWarning: Columns (0: MARGEM MÉDIA REVENDA, 1: PREÇO MÉDIO DISTRIBUIÇÃO, 2: DESVIO PADRÃO DISTRIBUIÇÃO, 3: PREÇO MÍNIMO DISTRIBUIÇÃO, 4: PREÇO MÁXIMO DISTRIBUIÇÃO, 5: COEF DE VARIAÇÃO DISTRIBUIÇÃO) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('gasolina_2010+.csv')

### 2.Investigue as colunas e entenda o conjunto de dados usando o head() e info()

In [ ]:
df3.head()
# retorna as 5 primeiras linhas de um DataFrame ou Series
df3.info()
# retorna as informações das colunas
# possui muitos erros de valores, nesse caso do elemento 14 ao 17 veio errado, é um int n um objeto, além das datas, que n vinheram como datetime

<class 'pandas.DataFrame'>
Index: 120823 entries, 0 to 78184
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  str
 2   DATA FINAL                     120823 non-null  str
 3   REGIÃO                         120823 non-null  str
 4   ESTADO                         120823 non-null  str
 5   PRODUTO                        120823 non-null  str
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  str
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(2), object(6), str(6)
memory usage: 18.4+ MB

### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [ ]:
type(df3['DATA INICIAL'][0])
# as Series parecem com arrays, após pegar a coluna do DataFrame retorna uma Series, é possível manipular essa Series

str

### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime.

In [6]:
df3['DATA INICIAL'] = pd.to_datetime(df3['DATA INICIAL'])
df3['DATA FINAL'] = pd.to_datetime(df3['DATA FINAL'])
df3

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78180,120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78181,120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78182,120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78183,120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78184,120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência.

In [49]:
df3['ANO_MES'] = df3['DATA FINAL'].apply(lambda x: '{}'.format(x.year)) +  df3['DATA FINAL'].apply(lambda x: '-{:02d}'.format(x.month))
# bem legal, porém difícil

### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [27]:
df3.value_counts()

Unnamed: 0  DATA INICIAL  DATA FINAL  REGIÃO        ESTADO              PRODUTO           NÚMERO DE POSTOS PESQUISADOS  UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  PREÇO MÍNIMO DISTRIBUIÇÃO  PREÇO MÁXIMO DISTRIBUIÇÃO  COEF DE VARIAÇÃO DISTRIBUIÇÃO
0           2004-05-09    2004-05-15  CENTRO OESTE  DISTRITO FEDERAL    ETANOL HIDRATADO  127                           R$/l               1.288                0.016                  1.190                 1.350                  0.463                0.012                      0.825                     0.11                        0.4201                     0.9666                     0.133                           1
1           2004-05-09    2004-05-15  CENTRO OESTE  GOIAS               ETANOL HIDRATADO  387                           R$/l               1.162                0.114                  0.890                 1.449                  0.399                0.098                      0.763                     0.088                       0.5013                     1.05                       0.115                           1
2           2004-05-09    2004-05-15  CENTRO OESTE  MATO GROSSO         ETANOL HIDRATADO  192                           R$/l               1.389                0.097                  1.180                 1.760                  0.419                0.070                      0.97                      0.095                       0.5614                     1.161                      0.098                           1
3           2004-05-09    2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL  ETANOL HIDRATADO  162                           R$/l               1.262                0.070                  1.090                 1.509                  0.432                0.055                      0.83                      0.119                       0.5991                     1.22242                    0.143                           1
4           2004-05-09    2004-05-15  NORDESTE      ALAGOAS             ETANOL HIDRATADO  103                           R$/l               1.181                0.078                  1.050                 1.400                  0.24                 0.066                      0.941                     0.077                       0.7441                     1.0317                     0.082                           1
                                                                                                                                                                                                                                                                                                                                                                                                                               ..
120818      2021-04-25    2021-05-01  NORTE         RORAIMA             OLEO DIESEL S10   12                            R$/l               4.582                0.056                  4.510                 4.690                 -99999.0              0.012                     -99999.0                  -99999.0                    -99999.0                   -99999.0                   -99999.0                         1
120819      2021-04-25    2021-05-01  SUL           SANTA CATARINA      OLEO DIESEL S10   100                           R$/l               4.141                0.187                  3.838                 4.739                 -99999.0              0.045                     -99999.0                  -99999.0                    -99999.0                   -99999.0                   -99999.0                         1
120820      2021-04-25    2021-05-01  SUDESTE       SAO PAULO           OLEO DIESEL S10   886                           R$/l               4.246                0.216                  3.769                 5.199                 -99999.0              0.051                     -99999.0                  -99999.0                    -99999.0                   -99999.0                   -99999.0                         1
120821      2021-04-25    2021-05-01  NORDESTE      SERGIPE             OLEO DIESEL S10   33                            R$/l               4.464                0.205                  4.190                 4.699                 -99999.0              0.046                     -99999.0                  -99999.0                    -99999.0                   -99999.0                   -99999.0                         1
120822      2021-04-25    2021-05-01  NORTE         TOCANTINS           OLEO DIESEL S10   18                            R$/l               4.352                0.156                  4.199                 4.699                 -99999.0              0.036                     -99999.0                  -99999.0                    -99999.0                   -99999.0                   -99999.0                         1
Name: count, Length: 120823, dtype: int64

### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [26]:
gasolina_comum = df3[df3['PRODUTO'] == 'GASOLINA COMUM']
gasolina_comum

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
9256,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012
9257,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021
9258,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036
9259,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018
9260,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78083,120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78084,120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78085,120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78086,120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78087,120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [ ]:
df3['DATA FINAL'] = pd.to_datetime(df3['DATA FINAL'])
df3[(df3['DATA INICIAL'].dt.year == 2008) & (df3['DATA INICIAL'].dt.month == 8)]['PREÇO MÉDIO REVENDA'].mean()

np.float64(9.29223139158576)

### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [14]:
df3[(df3['DATA INICIAL'].dt.year == 2014) & (df3['DATA INICIAL'].dt.month == 5)]['PREÇO MÉDIO REVENDA'].mean()

np.float64(9.992809523809525)

### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [50]:
df3[(df3['PRODUTO'] == 'GASOLINA COMUM') & (df3['PREÇO MÉDIO REVENDA'] > 5)]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO_MES,MES
55563,98201,2018-05-20,2018-05-26,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.053,0.184,...,5.459,0.797,0.036,4.256,0.132,4.07,4.4685,0.031,2018-05,5
55709,98347,2018-05-27,2018-06-02,NORTE,ACRE,GASOLINA COMUM,11,R$/l,5.035,0.133,...,5.400,0.799,0.026,4.236,0.152,4.07,4.4542,0.036,2018-06,6
55855,98493,2018-06-03,2018-06-09,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.038,0.197,...,5.459,0.664,0.039,4.374,0.084,4.2316,4.576,0.019,2018-06,6
55873,98511,2018-06-03,2018-06-09,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,414,R$/l,5.016,0.144,...,5.599,0.541,0.029,4.475,0.108,4.1667,4.8321,0.024,2018-06,6
56008,98646,2018-06-10,2018-06-16,NORTE,ACRE,GASOLINA COMUM,38,R$/l,5.031,0.206,...,5.459,0.686,0.041,4.345,0.081,4.2149,4.518,0.019,2018-06,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78083,120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,...,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,5
78084,120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,...,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,5
78085,120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,...,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,5
78086,120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,...,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,5
78087,120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,...,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,5

### 11. Qual a média de preço dos estados da região sul em 2012?

In [9]:
df3['DATA FINAL'] = pd.to_datetime(df3['DATA FINAL'])
df3[(df3['REGIÃO'] == 'SUL') & (df3['DATA FINAL'].dt.year == 2012)]['PREÇO MÉDIO REVENDA'].mean()

np.float64(9.842052564102564)

### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [46]:
df3['MES'] = df3['DATA FINAL'].apply(lambda x: x.month)
df_rio = df3[df3['ESTADO'] == 'RIO DE JANEIRO']

In [54]:
df_month_rio = df_rio.groupby('ANO_MES')[['PREÇO MÉDIO REVENDA', 'MES']].last()
dezembro = df_month_rio[df_month_rio['MES'] == 12]

In [55]:
(df_month_rio[df_month_rio['MES'] == 12] / df_month_rio[df_month_rio['MES'] == 12].shift(1) - 1) * 100

         PREÇO MÉDIO REVENDA  MES
ANO_MES
2004-12                  NaN  NaN
2005-12            12.338063  0.0
2006-12            -0.878638  0.0
2007-12             0.720222  0.0
2008-12            14.466447  0.0
2009-12            -4.949543  0.0
2010-12             0.202224  0.0
2011-12             1.261352  0.0
2012-12             5.630294  0.0
2013-12           -21.084906  0.0
2014-12             7.770472  0.0
2015-12            17.304493  0.0
2016-12            -2.269504  0.0
2017-12             9.869376  0.0
2018-12            35.358873  0.0
2019-12            24.951204  0.0
2020-12            -1.483989  0.0

### DESAFIO: Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e menores preços foram registrados.

In [71]:
df_max = df3.groupby('ANO_MES').max(numeric_only=True)['PREÇO MÉDIO REVENDA']
df_min = df3.groupby('ANO_MES').min(numeric_only=True)['PREÇO MÉDIO REVENDA']

idx_max = df3.groupby('ANO_MES')['PREÇO MÉDIO REVENDA'].idxmax()
idx_min = df3.groupby('ANO_MES')['PREÇO MÉDIO REVENDA'].idxmin()

In [61]:
df_diff = pd.DataFrame()

In [ ]:
df_diff['abs_diff'] = df_max - df_min
df_diff['percent_diff'] = (df_max - df_min) / df_min * 100
df_diff['max'] = df_max
df_diff['min'] = df_min

In [78]:
df_diff['ESTADO_MAX'] = df3.loc[idx_max, :]['ESTADO'].values
df_diff['ESTADO_MIN'] = df3.loc[idx_min, :]['ESTADO'].values

ValueError: Length of values (353) does not match length of index (204)

In [65]:
df_diff

         abs_diff  percent_diff
ANO_MES
2004-05    38.562   5034.203655
2004-06    38.159   4302.029312
2004-07    38.182   4247.163515
2004-08    38.053   3809.109109
2004-09    38.031   3806.906907
...           ...           ...
2021-01    95.521   3539.125602
2021-02    98.645   3524.294391
2021-03   104.751   3810.512914
2021-04   102.370   3625.000000
2021-05   101.091   3579.709632

[204 rows x 2 columns]